---
title: "AlbertAnalysis"
author: "Sean Collins"
start date: "December 7, 2015"
revised data: "December 9, 2015"
output: html_document
---

### Data analysis performed for Albert's physiology of exercise lab report

Based on the Astrand et al, 1964 data set

### Hypotheses 
1. Inverse relationship between vo2max and resting heart rate
2. Submaximal heart rate and max heart rate relate to max vo2


### Analysis strategy

The only variable that needs modification is vo2, currently in absolute units (L/min), makes more sense to change units to ml/kg/min

#### Hypothesis 1

Scatter plot and linear regression model between resting heart rate and vo2max 

#### Hypothesis 2

Scatter plot and linear regression model between maximal heart rate and vo2max

Scatter plot and linear regression model between submaximal heart (stage 2 of the exercise test) and vo2max. Stage 2 was chosen because all subjects were performing the same rate of work and none of the subjects had achieved their vo2max yet (i.e. some had reached max at the rate of work associated with stage 3 of the protocol)

### Analysis steps
1. Load R packages, load data, organize data for analysis
2. Descriptive statistics of relevant variables
3. Univariate distributions with boxplots
4. Bivariate distributions with scatterplots
5. Linear regression

For the sake of presentation 4 & 5 will be combined so that output releated to the linear regression model will follow the scatterplot of the same variables.


### Load and clean data for analysis 
```{r}
library(dplyr)
library(ggplot2)

setwd("~/physexlab/Astrand_1964")
data <- read.csv("data.csv")
data <- mutate(data,VO2_mlkg = (VO2*1000)/weight)
data<-select(data, age, height, weight, stage, rest, max, HR, VO2_mlkg)
rest<-filter(data,rest==1)
rest<-select(rest,age, height, weight,HR, VO2_mlkg)
rest<- rename(rest, restHR = HR, restVO2_mlkg = VO2_mlkg)
max<-filter(data,max==1)
max<-select(max,HR, VO2_mlkg)
max<-select(max,age, height, weight,HR, VO2_mlkg)
max<- rename(max, maxHR = HR, maxVO2_mlkg = VO2_mlkg)
stage2<-filter(data,stage==2)
stage2<-select(stage2,HR, VO2_mlkg)
stage2<- rename(stage2, stage2HR = HR, stage2VO2_mlkg = VO2_mlkg)
```

par(mfrow = c(2, 3))
with(data, plot(stage, VO2_mlkg, xlab="Stage", ylab="VO2 (ml/kg/min)"))
with(data, plot(stage, METs, xlab = "Stage", ylab="METs"))
with(data, plot(stage, Q_mlkg, xlab="Stage", ylab="Cardiac Output (ml/kg/min)"))
with(data, plot(stage, AV_diff, xlab="Stage", ylab="(a-v)O2 difference"))
with(data, plot(stage, HR, xlab="Stage", ylab="Heart Rate"))
with(data, plot(stage, SV,xlab="Stage", ylab="Stroke Volume"))


dev.copy(png, file = "plot.png", width = 480, height = 480)
dev.off()

par(mfrow = c(1, 1))
with(data, plot(stage, VO2_mlkg, xlab="Stage", ylab="VO2 (ml/kg/min)"))
dev.copy(png, file = "VO2.png", width = 480, height = 480)
dev.off()

par(mfrow = c(1, 1))
with(data, plot(stage, Q_mlkg, xlab="Stage", ylab="Cardiac Output (ml/kg/min)"))
dev.copy(png, file = "Q.png", width = 480, height = 480)
dev.off()

par(mfrow = c(1, 1))
with(data, plot(stage, AV_diff, xlab="Stage", ylab="(a-v)O2 difference"))
dev.copy(png, file = "AV.png", width = 480, height = 480)
dev.off()


par(mfrow = c(1, 1))
with(data, plot(stage, HR, xlab="Stage", ylab="Heart Rate"))
dev.copy(png, file = "hr.png", width = 480, height = 480)
dev.off()

par(mfrow = c(1, 1))
with(data, plot(stage, SV,xlab="Stage", ylab="Stroke Volume"))
dev.copy(png, file = "sv.png", width = 480, height = 480)
dev.off()


write.csv(data,"AstrandData1964.csv")

rest <- filter(data,stage == 0)
hist(rest$heartVolume)
plot(data$stage,data$VO2)
hist(data$AV_diff)

#Confirm that VO2 in L/min is the same as Q * AV_diff in this data set
data <- mutate(data,calcVO2 = AV_diff * Q)
data$stage <- as.factor(data$stage)
by_stage <- group_by(data,stage)
summarize(by_stage, mean(VO2), mean(calcVO2))

summarize(by_stage, mean(Q), min(Q), max(Q))

#A function to calculate VO2Max_est
vo2_function <- function(Q, AV_diff){
	vo2<-Q*AV_diff
}


